version: "3.8"

services:
  mongo:
    image: mongo
    container_name: meu-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
